## YAML Template.
---
application:
    database:
        mongo:
            host: localhost
            port: 27017
            authenticationDatabase: admin
            userName:
            password:
            connectionsPerHost: 10
            bulkWriteNumber: 1000
            bulkWriteTimeout: 10
            
    migrateSTF:
        maxMigrationSTFThread: 10
        migratedFileNumberPerThread: 10000
        
    createFileDataNumber: 1000000
    documentNumberPerAnInsert: 100