## YAML Template.
---
application:
    database:
        mongo:
            host: localhost
            port: 27017
            authenticationDatabase: admin
            userName:
            password:
            connectionsPerHost: 10
            bulkWriteNumber: 10
            bulkWriteTimeout: 10
            
    migrateSTF:
        maxMigrationSTFThread: 1
        migratedFileNumberPerThread: 1000000
        
    createFileDataNumber: 100
    documentNumberPerAnInsert: 10